# Values for skaffold testing during dev of the controller

logVerbosity: 8

requestAnalysis: true

# Can provide creds in external secret using `existingCredentialsSecret` key or this inline
# uses this inline for dev purposes
credentials:
  users:
    - username: admin
      password: foobar

anchoreEndpoint: "http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228"
policySelectors:
  - Selector:
      ResourceType: namespace
      SelectorKeyRegex: Name
      SelectorValueRegex: testns
    PolicyReference:
      Username: admin
      PolicyBundleId: bundle1
    Mode: policy
  - Selector:
      ResourceType: pod
      SelectorKeyRegex: stage
      SelectorValueRegex: testing
    PolicyReference:
      Username: admin
      PolicyBUndleId: bundle2
    Mode: policy
  - Selector:
      ResourceType: image
      SelectorKeyRegex: .*
      SelectorValueRegex: ^alpine.*
    PolicyReference:
      Username: admin
      PolicyBundleId: bundle2
    Mode: policy
  - Selector:
      ResourceType: image
      SelectorKeyRegex: .*
      SelectorValueRegex: .*
    PolicyReference:
      Username: admin
      PolicyBundleId: bundle2
    Mode: analysis
